version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
  db:
   image: mysql:8.0
   environment:
    
     MYSQL_ROOT_PASSWORD: ${DB_ROOT_SIFRE}
     MYSQL_DATABASE: GYM_WEB
   volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_SIFRE}
    depends_on:
      - db
  
volumes:
  db_data:
